marketing/Home/urls.py
from django.urls import path
from Home.views import BannerView

app_name='Home'

urlpatterns = [
    path('', BannerView.as_view(), name='Banner'),
]

marketing/Our_Service/urls.py
from django.urls import path
from Our_Service.views import HomepageView

app_name='Service'

urlpatterns = [
    path('Service/', HomepageView.as_view(), name='Service'),
]

marketing/Team/urls.py
from django.urls import path
from Team.views import Homepage_team_views

app_name='Team'

urlpatterns = [
    path('Team/',Homepage_team_views.as_view(), name='Team'),
]

marketing/Work/urls.py
from django.urls import path
from Work.views import Homepage_workview

app_name='Work'

urlpatterns = [
    path('Work/', Homepage_workview.as_view(), name='Work'),
]

marketing/about/urls.py
from django.urls import path
from about.views import AboutView

app_name='About'

urlpatterns = [
    path('About/', AboutView.as_view(), name='About'),
]

marketing/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    path('', include('Our_Service.urls')),
    path('', include('Team.urls')),
    path('', include('Work.urls')),
    path('', include('about.urls'))
]




if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

marketing/Contact/models.py
from django.db import models

class Contact_Model(models.Model):
    name = models.CharField(max_length=100)
    Email = models.EmailField()
    Subject = models.CharField(max_length=100)
    Message = models.CharField(max_length=255)

marketing/Home/models.py
from django.db import models

class Banner(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='Banner/%Y/%m/%d')

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Banner'
        verbose_name_plural = 'Banners'
    

marketing/Our_Service/models.py
from django.db import models
from Our_Service.abstract import BaseModel, OrderModel

class Homepage(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Homepage'
        verbose_name_plural = 'Homepages'


class department(BaseModel, OrderModel):
    image = models.ImageField(upload_to='department/%Y/%m/%d')
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'department'
        verbose_name_plural = 'department'

marketing/Team/models.py
from django.db import models
from Our_Service.abstract import BaseModel, OrderModel

class Homepage_Team(models.Model):
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title
    

    class Meta:
        verbose_name = 'Homepage_Team'
        verbose_name_plural = 'Homepage_Teams'

class Team(BaseModel, OrderModel):
    image = models.ImageField(upload_to='Team/%Y/%m/%d')
    name = models.CharField(max_length=50)
    about_the_worker = models.CharField(max_length=255)
    facebook_link = models.URLField(null=True, blank=True)
    twitter_link = models.URLField(null=True, blank=True)
    linkedin_link = models.URLField(null=True, blank=True)
    instagram_link = models.URLField(null=True, blank=True)

    def __str__(self) -> str:
        return self.name
    

    class Meta:
        verbose_name = 'Team'
        verbose_name_plural = 'Teams'

class Homepage_Testimonial(models.Model):
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.title
    

    class Meta:
        verbose_name = 'Homepage_Testimonial'
        verbose_name_plural = 'Homepage_Testimonials'


class Testimonial(BaseModel, OrderModel):
    image = models.ImageField(upload_to='Testimonial/%Y/%m/%d')
    name = models.CharField(max_length=50)
    information = models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.name
    

    class Meta:
        verbose_name = 'Testimonial'
        verbose_name_plural = 'Testimonials'

marketing/Work/models.py
from django.db import models
from Our_Service.abstract import OrderModel

class Homepage_work(models.Model):
    title = models.CharField(max_length=50)
    sub_title = models.CharField(max_length=100)
    

    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'Homepage_work'
        verbose_name_plural = 'Homepage_works'



class work_department(OrderModel):
    icon = models.ImageField(upload_to='work_department/%Y/%m/%d')
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.title


    class Meta:
        verbose_name = 'Work_department'
        verbose_name_plural = 'Work_departments'

marketing/about/models.py
from django.db import models


class About(models.Model):
    image = models.ImageField(upload_to='aboutmodel/%Y/%m/%d')
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.title
    
    class Meta:
        verbose_name = 'AboutModel'
        verbose_name_plural = 'AboutModels'

marketing/Contact/views.py
from django.shortcuts import render

# Create your views here.

marketing/Home/views.py
from django.shortcuts import render
from django.views.generic import ListView
from Home.models import Banner

class BannerView(ListView):
    model = Banner
    template_name = 'Home.html'

marketing/Our_Service/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView
from Our_Service.models import Homepage, department

class HomepageView(ListView):
    template_name = 'service.html'

    def get_queryset(self) -> QuerySet[Any]:
        qs = Homepage.objects.all()
        return qs
    

    def get_context_data(self, **kwargs: Any):
        data = super().get_context_data(**kwargs)
        data['department'] = department.objects.all()
        return data

marketing/Team/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.views.generic import ListView
from Team.models import Homepage_Team, Team, Homepage_Testimonial, Testimonial

class Homepage_team_views(ListView):
    template_name = 'Team.html'

    def get_queryset(self) -> QuerySet[Any]:
        qs = Homepage_Team.objects.all()
        return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data= super().get_context_data(**kwargs)
        data['Team'] = Team.objects.all()
        data['homepage_testimonials'] = Homepage_Testimonial.objects.all()
        data['Testimonial'] = Testimonial.objects.all()
        return data

marketing/Work/views.py
from django.shortcuts import render
from typing import Any
from django.views.generic import ListView
from Work.models import Homepage_work, work_department
from django.db.models.query import QuerySet

class Homepage_workview(ListView):
    template_name = 'work.html'


    def get_queryset(self) -> QuerySet[Any]:
      qs = Homepage_work.objects.all()
      return qs
    
    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
         data = super().get_context_data()
         data['departments'] = work_department.objects.all()
         return data

marketing/about/views.py
from django.shortcuts import render
from django.views.generic import ListView
from about.models import About

class AboutView(ListView):
    model = About
    template_name = 'about.html'

marketing/templates/Home.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
    <!-- end header section -->
    <!-- slider section -->
    <section class=" slider_section ">

        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
         
          <div class="carousel-inner">
           
            <div class="carousel-item active">
               
              <div class="container">
              
              
                <div class="row">
                    {% for i in object_list %}  
                    
                  <div class="col-md-6 ">
                    
                    <div class="detail_box">
                        
                      <h1>
                       {{i.title}}
                      </h1>
                      <p>
                       {{i.sub_title}}
                      </p>
                      <div class="btn-box">
                        <a href="" class="btn-1">
                          Contact Us
                        </a>
                        <a href="" class="btn-2">
                          Get A Quote
                        </a>
                      </div>
                      
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="img-box">
                      <img src="{{i.image.url}}" alt="">
                      
                    </div>
                   
                  </div>
                  {% endfor %}      
                </div>
               
              </div>
             
            </div>
       
           
        </div>
         
          <div class="carousel_btn-container">
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="sr-only">Previous</span>
            </a>
            
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="sr-only">Next</span>
            </a>
          
          </div>
        
        </div>
      </section>
      <!-- end slider section -->
    </div>
  {% endblock %}

marketing/templates/Team.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
  <section class="team_section layout_padding2-bottom">
    <div class="container">
      <div class="heading_container">
        {% for i in object_list %}
        <h2>
          {{i.title}}
        </h2>
        <p>
          {{i.sub_title}}
        </p>
      </div>
      {% endfor %}
    </div>
    <div class="team_container">
      <div class="box b-1">
        <div class="img-box">
          {% for b in Team %}
          <img src="{{b.image.url}}" alt="">
        </div>
        <div class="detail-box">
          <h5>
            {{b.name.url}}
          </h5>
          <p>
            {{b.about_the_worker}}
          </p>
          <div class="social_box">
            <a href="">
              <img src="{% static 'images/facebook.png' %}" alt="">
            </a>
            <a href="{{b.twitter_link.url}}">
              <img src="{% static 'images/twitter.png' %}" alt="">
            </a>
            <a href="{{b.linkedin_link.url}}">
              <img src="{% static 'images/linkedin.png' %}" alt="">
            </a>
            <a href="{{b.instagram_link.url}}">
              <img src="{% static 'images/insta.png' %}" alt="">
            </a>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </section>

  <!-- end team section -->

  <!-- client section -->

  <section class="client_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container">
        {% for c in homepage_testimonials %}
        <h2>
          {{c.title}}
        </h2>
        <p>
          {{c.sub_title}}
        </p>
        {% endfor %}
      </div>
    </div>
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        {% for  d in Testimonial%}
        <div class="carousel-item {% if forloop.first %}active{% endif %}">
          <div class="container">
       
            <div class="box">
             
              <div class="img-box">
               
                <img src="{{d.image.url}}" alt="">
              </div>
              <div class="detail-box">
                <h6>
                  {{d.name}}
                </h6>
                <p>
                 {{d.information}}
                </p>
                <img src="{% static 'images/quote.png' %}" alt="">
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
      <div class="carousel_btn-container">
        <a class="carousel-control-prev" href="#carouselExampleControls"  role="button" data-slide="prev">
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls"  role="button" data-slide="next" data-slide-to="{{ forloop.counter }}" > 
          <span class="sr-only">Next</span>
        </a>
        
      </div>
    </div>

  </section>
{% endblock %}
  <!-- end client section -->

marketing/templates/about.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
  <!-- about section -->

  <section class="about_section">
    <div class="container">
     
      <div class="row">
      {% for i in object_list %}
        <div class="col-md-6">
          <div class="img-box">
            <img src="{{i.image.url}}" alt="">
            <h1></h1>
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                {{i.title}}
              </h2>
            </div>
            <p>
             {{object.sub_title}}
            </p>
          </div>
        </div>
      {% endfor %}
      </div>
      
    </div>
  </section>
{% endblock %}

marketing/templates/index.html

  <!-- about section -->

  <section class="about_section ">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="img-box">
            <img src="images/about-img2.png" alt="">
          </div>
        </div>
        <div class="col-md-6">
          <div class="detail-box">
            <div class="heading_container">
              <h2>
                About Us
              </h2>
            </div>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
              dolore magna aliqua. Ut enim ad minim veniam, quis nostrud
            </p>
            <a href="">
              Read More
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end about section -->


  <!-- service section -->
  <section class="service_section layout_padding">
    <div class="container-fluid">
      <div class="heading_container">
        <h2>
          Our Services
        </h2>
        <p>
          consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
      </div>

      <div class="service_container">
        <div class="box">
          <div class="img-box">
            <img src="images/s-1.png" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Brand Promotion
            </h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="images/s-2.png" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Video Marketing

            </h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="images/s-3.png" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Site Analysis
            </h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="images/s-4.png" alt="">
          </div>
          <div class="detail-box">
            <h5>
              Social Media Marketing
            </h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
          </div>
        </div>
        <div class="box">
          <div class="img-box">
            <img src="images/s-5.png" alt="">
          </div>
          <div class="detail-box">
            <h5>
              SEO Optimization
            </h5>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit,
            </p>
          </div>
        </div>
      </div>
      <div class="btn-box">
        <a href="">
          Read More
        </a>
      </div>
    </div>
  </section>
  <!-- end service section -->

  <!-- work section -->

marketing/templates/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Seotech</title>

  <!-- slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="{% static 'https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.1.3/assets/owl.carousel.min.css' %}" />

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />

  <!-- fonts style -->
  <link href="{% static 'https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap' %}" rel="stylesheet">
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
</head>

<body>

  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="index.html">
            <span>
              Seotech
            </span>
          </a>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="s-1"> </span>
            <span class="s-2"> </span>
            <span class="s-3"> </span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="d-flex mx-auto flex-column flex-lg-row align-items-center">
              <ul class="navbar-nav  ">
                <li class="nav-item active">
                  <a class="nav-link" href="index.html">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="about.html"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="service.html"> Services </a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#contactLink">Contact Us</a>
                </li>
              </ul>
            </div>
            <div class="quote_btn-container ">
              <a href="">
                <img src="{% static 'images/call.png' %}" alt="">
                <span>
                  Call : + 01 1234567890
                </span>
              </a>
              <form class="form-inline">
                <button class="btn  my-2 my-sm-0 nav_search-btn" type="submit"></button>
              </form>
            </div>
          </div>
        </nav>
      </div>
    </header>

    {% block content %}

    {% endblock %}

    
<div class="footer_bg">

    <!-- contact section -->
    <section class="contact_section layout_padding" id="contactLink">
      <div class="container">
        <div class="heading_container">
          <h2>
            Get In touch
          </h2>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-8 mx-auto">
            <form>
              <div class="form-row">
                <div class="form-group col-md-6">
                  <input type="text" class="form-control" id="inputName4" placeholder="Name ">
                </div>
                <div class="form-group col-md-6">
                  <input type="email" class="form-control" id="inputEmail4" placeholder="Email id">
                </div>

              </div>
              <div class="form-row">
                <div class="form-group col">
                  <input type="text" class="form-control" id="inputSubject4" placeholder="Subject">
                </div>
              </div>
              <div class="form-group">
                <input type="text" class="form-control" id="inputMessage" placeholder="Message">
              </div>
              <div class="d-flex justify-content-center">
                <button type="submit" class="">Send</button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>


    <!-- end contact section -->



    <!-- info section -->
    <section class="info_section layout_padding2">
      <div class="container">
        <div class="row">
          <div class="col-md-3">
            <div class="info_logo">
              <h3>
                Seotech
              </h3>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor indidunt ut labore et
                dolore magna
              </p>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info_links">
              <h4>
                BASIC LINKS
              </h4>
              <ul class=" ">
                <li class=" active">
                  <a class="" href="index.html">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="">
                  <a class="" href="about.html"> About</a>
                </li>
                <li class="">
                  <a class="" href="{% url 'Service:Service' %}"> Services </a>
                </li>
                <li class="">
                  <a class="" href="#contactLink">Contact Us</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info_contact">
              <h4>
                CONTACT DETAILS
              </h4>
              <a href="">
                <div class="img-box">
                  <img src="{% static 'images/telephone-white.png' %}" width="12px" alt="">
                </div>
                <p>
                  +01 1234567890
                </p>
              </a>
              <a href="">
                <div class="img-box">
                  <img src="{% static 'images/envelope-white.png' %}" width="18px" alt="">
                </div>
                <p>
                  demo@gmail.com
                </p>
              </a>
            </div>
          </div>
          <div class="col-md-3">
            <div class="info_form ">
              <h4>
                NEWSLETTER
              </h4>
              <form action="">
                <input type="email" placeholder="Enter your email">
                <button>
                  Subscribe
                </button>
              </form>
              <div class="social_box">
                <a href="https://www.facebook.com/">
                  <img src="{% static 'images/info-fb.png' %}" alt="">
                </a>
                <a href="https://twitter.com/">
                  <img src="{% static 'images/info-twitter.png' %}" alt="">
                </a>
                <a href="https://www.linkedin.com/">
                  <img src="{% static 'images/info-linkedin.png' %}" alt="">
                </a>
                <a href="https://www.youtube.com/">
                  <img src="{% static 'images/info-youtube.png' %}" alt="">
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end info_section -->


    <!-- footer section -->
    <section class="container-fluid footer_section">
      <div class="container">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved By
          <a href="{% static 'https://html.design/' %}">Free Html Templates</a>
        </p>
      </div>
    </section>
    <!-- footer section -->

  </div>

  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>

</body>

</html>

marketing/templates/service.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}
  <!-- service section -->
  <section class="service_section layout_padding">
    <div class="container-fluid">
      <div class="heading_container">
        {% for i in object_list %}
        <h2>
        {{i.title}}
        </h2>
        <p>
          {{i.sub_title}}
        </p>
      </div>
        {% endfor %}
      <div class="service_container">
        <div class="box">
          {% for department in department %}
          <div class="img-box">
            <img src="{{department.image.url}}" alt="">
          </div>
          <div class="detail-box">
            <h5>
              {{department.title}}
            </h5>
            <p>
            {{department.sub_title}}
            </p>
            {% endfor %}
          </div>
        </div>
    </div>
  </section>
  <!-- end service section -->
{% endblock %}

marketing/templates/work.html
{% extends 'layouts/base.html' %}
{% load static %}
{% block content %}

<!-- work section -->
<section class="work_section layout_padding">
    <div class="container">
      
      <div class="heading_container">
        {% for i in object_list %}
        <h2>
          {{i.title}}
        </h2>
        <p>
         {{i.sub_title}}
        </p>
        {% endfor %}
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="detail_container">
            {% for department in departments %}
            <div class="box b-1">
              <div class="top-box">
                <div class="icon-box">
                  <img src="{{department.icon.url}}" alt="">
                </div>
                <h5>
                {{department.title}}
                </h5>
              </div>
              <div class="bottom-box">
                <p>
                  {{department.sub_title}}
                </p>
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="img-box">
            <img src="{% static 'images/work-img.png' %}" alt="">
          </div>
        </div>
      </div>
        </a>
      </div>
    </div>
  </section>
  <!-- end work section -->
  {% endblock %}